In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('./data/rows.csv')
df['total'] = 1

In [23]:
[n for n in df.NCName.unique() if 'TOL' in str(n)]

['GREATER TOLUCA LAKE NC']

In [24]:
toluca_df = df[df.NCName == 'GREATER TOLUCA LAKE NC']

In [41]:
tol_group = toluca_df.groupby(['RequestType', ]).total.count().reset_index()

In [43]:
toluca_sorted = tol_group.sort_values(by=['total'], ascending=False)

In [52]:
toluca_sorted

                   RequestType  total
0                  Bulky Items   1304
3             Graffiti Removal    578
4          Homeless Encampment    257
6   Metal/Household Appliances    251
5       Illegal Dumping Pickup    174
2             Electronic Waste     76
8                        Other     66
1          Dead Animal Removal     41
7   Multiple Streetlight Issue     31
10    Single Streetlight Issue     23
9           Report Water Waste      2

In [61]:
toluca_device = toluca_df[toluca_df.RequestSource == 'Mobile App' ]
mobile_app = toluca_device.groupby(['RequestType', 'Status' ]).total.count().reset_index()
mobile_app_sorted = mobile_app.sort_values(by=['total'], ascending=False)
mobile_app_sorted

                   RequestType     Status  total
1                  Bulky Items     Closed    359
7             Graffiti Removal     Closed    203
6             Graffiti Removal  Cancelled    192
11         Homeless Encampment     Closed    126
22                       Other     Closed     37
17  Metal/Household Appliances     Closed     34
14      Illegal Dumping Pickup     Closed     34
4             Electronic Waste     Closed     17
24    Single Streetlight Issue     Closed     13
2                  Bulky Items       Open     12
21                       Other  Cancelled     12
13         Homeless Encampment    Pending     10
20  Multiple Streetlight Issue       Open     10
12         Homeless Encampment       Open     10
3          Dead Animal Removal     Closed      8
9             Graffiti Removal       Open      7
19  Multiple Streetlight Issue     Closed      3
18  Metal/Household Appliances       Open      2
23          Report Water Waste     Closed      2
10         Homeless Encampment  Cancelled      1
15      Illegal Dumping Pickup       Open      1
16      Illegal Dumping Pickup    Pending      1
8             Graffiti Removal    Forward      1
5             Electronic Waste       Open      1
0                  Bulky Items  Cancelled      1

In [71]:
mobile_open_pending = toluca_df[(toluca_df.RequestSource == 'Mobile App') & (toluca_df.Status == 'Open' ) | (toluca_df.Status == 'Pending' )  ]

In [ ]:
'Latitude', 'Longitude'